// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function getFuelForModule(mass) {
  return Math.floor(mass / 3.0) - 2.0;
}

console.log(Belt_Array.reduce(Belt_Array.map(Belt_Array.keep(Fs.readFileSync("./src/input1", "utf8").split("\n"), (function (str) {
                    return str !== "";
                  })), (function (prim) {
                return Number(prim);
              })), 0.0, (function (acc, mass) {
            return acc + getFuelForModule(mass);
          })));

exports.getFuelForModule = getFuelForModule;
/*  Not a pure module */
